ID-B-4.4
AlexeyVolkov2023/HelpAnimal pull request #13
Opened 2024-08-25 11:53 UTC by AlexeyVolkov2023

Создал классы Breed, Spacies, создал рекорды Breedid, Speciesid, IdentifierAnimal. Написал конфигурацию для Breed и Species, поправил конфигурацию Animal

2024-08-25 11:59 UTC, AlexeyVolkov2023 commented on backend/src/HelpAnimal.Domain/Models/IdentifierAnimal.cs
> +
Получилось сделать миграцию только после добавления пустого конструктора, но так как это VO EF же не должен создавать отдельную таблицу

2024-08-26 06:33 UTC, YADARAN1 requested changes

2024-08-26 06:33 UTC, YADARAN1 commented on backend/src/HelpAnimal.Infrastructure/Configuration/BreedConfiguration.cs
> +        builder.ToTable("Breeds");
snakecase, всё с маленькой буквы

2024-08-26 06:33 UTC, YADARAN1 commented on backend/src/HelpAnimal.Domain/Models/IdentifierAnimal.cs
> +
У тебя возможно ошибка из-за несоответствия имён, у тебя в конструкторах(я в breed увидел Breedid), измени везде на обычное название "id"

2024-08-26 06:33 UTC, YADARAN1 commented on backend/src/HelpAnimal.Domain/Models/IdentifierAnimal.cs
> +
И потом протестируй, не забудь, удалить конструктор публичный из IdentifierAnimal и второй сделай приватным

2024-08-26 06:33 UTC, YADARAN1 commented on backend/src/HelpAnimal.Infrastructure/Configuration/SpeciesConfiguration.cs
> +        builder.ToTable("Species");
такая же история, всё с маленькой

2024-08-26 06:33 UTC, YADARAN1 commented on backend/src/HelpAnimal.Infrastructure/HelpAnimalDbContext.cs
> +    public DbSet<Species> Specieses { get; set; }
убери DbSet<Animal> Animals, мы через волонтёра(агрегат) взаимодействуем с животным

2024-08-27 17:48 UTC, AlexeyVolkov2023 commented on backend/src/HelpAnimal.Infrastructure/Migrations/HelpAnimalDbContextModelSnapshot.cs
> -
Пока делал конфигурацию то создал две миграции без аптдейта, потом даже с удалением миграций не смог ничего сделать . пробовал удалить вольюм из докера , но образ почему-то не видел новый файл, хотя имя было такое-же . В конце-концов удалили и запустил образ заново

2024-08-28 06:50 UTC, KirillSachkov approved these changes

2024-08-28 06:58 UTC, YADARAN1 requested changes

2024-08-28 06:58 UTC, YADARAN1 commented on backend/src/HelpAnimal.Domain/Models/AnimalPhotosDetails.cs
> +   public List<AnimalPhoto>? Photos { get; }
Вот тут лучше писать не List, a IReadOnlyList, и убери знак вопроса

2024-08-28 06:58 UTC, YADARAN1 commented on backend/src/HelpAnimal.Domain/Models/PhoneNumber.cs
> +            throw new ArgumentException(
У тебя не должен здесь выкидываться Exception, добавь регулярное выражение

2024-08-28 06:58 UTC, YADARAN1 commented on backend/src/HelpAnimal.Domain/Models/RequisiteDetails.cs
> +    public List<Requisite>? Requisites { get; private set; }
Тут тоже поменяй на IReadOnlyList и без знака вопроса + убери private set

2024-08-28 06:58 UTC, YADARAN1 commented on backend/src/HelpAnimal.Domain/Models/SocialDetails.cs
> +    public List<SocialNetwork>? Networks { get; private set;}
Тут тоже поменяй на IReadOnlyList и без знака вопроса + убери private set

2024-08-28 06:58 UTC, YADARAN1 commented on backend/src/HelpAnimal.Domain/Models/Species.cs
> +    public string? Title { get;  }
знак вопроса убрать и снизу у тебя лист поменяй на IReadOnlyList и без знака вопроса

2024-08-28 06:58 UTC, YADARAN1 commented on backend/src/HelpAnimal.Domain/Models/VaccinationDetails.cs
> +    public List<Vaccination>? Vaccinations { get;  }
Тут тоже поменяй на IReadOnlyList и без знака вопроса

2024-08-28 06:58 UTC, YADARAN1 commented on backend/src/HelpAnimal.Domain/Models/Volunter.cs
> +    public PhoneNumber? Phone { get; private set; }
Убрать знак вопроса

2024-08-28 06:58 UTC, YADARAN1 commented on backend/src/HelpAnimal.Domain/Models/Volunter.cs
> +    public List<Animal>? Animals { get; private set; }
Убрать знак вопроса

2024-08-28 06:58 UTC, YADARAN1 commented on backend/src/HelpAnimal.Domain/Models/Volunter.cs
> +    public PhoneNumber? Phone { get; private set; }
Тут тоже поменяй на IReadOnlyList и без знака вопроса и добавь private readonly List<Pet> _pets = []

2024-08-28 06:58 UTC, YADARAN1 commented on backend/src/HelpAnimal.Domain/Models/Volunter.cs
> +            id,
![image](https://github.com/user-attachments/assets/a0c431de-ded2-4a22-9a62-98641aa6f174)
Нам при создании волонтёра не нужны животные, убери их

2024-08-28 06:58 UTC, YADARAN1 commented on backend/src/HelpAnimal.Infrastructure/Configuration/AnimalConfiguration.cs
> +            ai.ToJson();
в скобках название в snakecase стиле

2024-08-28 06:58 UTC, YADARAN1 commented on backend/src/HelpAnimal.Infrastructure/Configuration/AnimalConfiguration.cs
> +        builder.OwnsOne(a => a.AnimalAddress, aa =>
Сконфигурируй как ComplexProperty

2024-08-28 06:58 UTC, YADARAN1 commented on backend/src/HelpAnimal.Domain/Models/Animal.cs
> +    public IdentifierAnimal? Identifier { get; private set; }
Убрать знак вопроса

2024-08-28 06:58 UTC, YADARAN1 commented on backend/src/HelpAnimal.Domain/Models/Animal.cs
> +    public Address? AnimalAddress { get; private set; } = default!;
Убрать знак вопроса

2024-08-28 06:58 UTC, YADARAN1 commented on backend/src/HelpAnimal.Domain/Models/Animal.cs
> +    public PhoneNumber? Phone { get; private set; } // Номер телефона для связи с владельцем
Убрать знак вопроса

2024-08-28 06:58 UTC, YADARAN1 commented on backend/src/HelpAnimal.Domain/Models/Animal.cs
> +    public VaccinationDetails? AlreadyVaccinated { get; private set; }
Убрать знак вопроса

2024-08-28 07:02 UTC, KirillSachkov requested changes
Сделать исправления

2024-08-28 07:03 UTC, YADARAN1 commented on backend/src/HelpAnimal.Infrastructure/Migrations/HelpAnimalDbContextModelSnapshot.cs
> -
Скинь в технические вопросы, поможем тебе там

2024-08-28 12:38 UTC, merged