ID-B-4.1
AlexeyVolkov2023/HelpAnimal pull request #8
Opened 2024-08-15 12:21 UTC by AlexeyVolkov2023

Подключение EFCore, создание Docker-compose, создание конфигурационных классов, выполнение миграции, Use secrets тоже сделал

2024-08-15 12:22 UTC, AlexeyVolkov2023 commented
Подскажите насчет констант , в правильном направлении двигаюсь, нужно ли создавать константы для номера телефона ?

2024-08-15 13:06 UTC, YaraOduvanchik requested changes

2024-08-15 13:06 UTC, n-cherashev commented on backend/src/HelpAnimal.Domain/Models/HelpDetail.cs
> +    public Guid Id { get; private set; }
id не должно быть, это ValueObject

2024-08-15 13:06 UTC, n-cherashev commented on backend/src/HelpAnimal.Domain/Models/HelpDetail.cs
> +public class HelpDetail
Можно переименовать класс в Requisite, а поле Requisite переименовать в Title. Так будет понятнее

2024-08-15 13:06 UTC, n-cherashev commented on backend/src/HelpAnimal.Domain/Models/HelpDetail.cs
>      public string Requisite { get; set; } = default!; // Название реквизита
Переименовать лучше в Tiitle

2024-08-15 13:06 UTC, n-cherashev commented on backend/src/HelpAnimal.Infrastructure/Configuration/AnimalConfiguration.cs
> +        builder.Property(a => a.Status)
ValueObject нужно конфигурировать подругому. Вместо Property используй ComplexProperty

2024-08-15 13:06 UTC, n-cherashev commented on backend/src/HelpAnimal.Infrastructure/Configuration/AnimalConfiguration.cs
> +        builder.HasMany(a => a.Requisite)
После того как уберёшь id из HelpDetails, нужно сконфигурировать подругому, вот пример:

builder.OwnsOne(p => p.Requisites, rb =>
        {
            rb.ToJson();
            rb.OwnsMany(r => r.Requisite, reqb =>
            {
                reqb.Property(r => r.Title)
                    .IsRequired();
                reqb.Property(r => r.Description)
                    .IsRequired();
            });
        });

2024-08-15 13:06 UTC, n-cherashev commented on backend/src/HelpAnimal.Infrastructure/Configuration/AnimalPhotoConfiguration.cs
> +            .ValueGeneratedOnAdd();
Убрать везде метод ValueGeneratedOnAdd у id

2024-08-15 13:06 UTC, n-cherashev commented on backend/src/HelpAnimal.Infrastructure/Configuration/AnimalConfiguration.cs
> +            .ValueGeneratedOnAdd();
Убрать везде метод ValueGeneratedOnAdd у id

2024-08-15 13:06 UTC, n-cherashev commented on backend/src/HelpAnimal.Domain/Models/SocialNetwork.cs
> +    public Guid Id { get; private set; }
Тут не нужен id, это ValueObject

2024-08-15 13:06 UTC, n-cherashev commented on backend/src/HelpAnimal.Infrastructure/Configuration/HelpDetailsConfiguration.cs
> +public class HelpDetailsConfiguration : IEntityTypeConfiguration<HelpDetail>
Убрать этот класс, так как HelpDetail это ValueObject

2024-08-15 13:06 UTC, n-cherashev commented on backend/src/HelpAnimal.Infrastructure/Configuration/SocialNetworkConfiguration.cs
> +public class SocialNetworkConfiguration : IEntityTypeConfiguration<SocialNetwork>
Убрать этот класс, так как SocialNetwork это ValueObject

2024-08-15 13:06 UTC, n-cherashev commented on backend/src/HelpAnimal.Infrastructure/Configuration/VolunteerConfiguration.cs
> +            .ValueGeneratedOnAdd();
Убрать везде метод ValueGeneratedOnAdd у id

2024-08-15 13:06 UTC, YaraOduvanchik commented on backend/src/HelpAnimal.Infrastructure/Configuration/VolunteerConfiguration.cs
> +        builder.HasMany(v => v.SocialNetworks)
Переделать, выше я приводил пример как конфигурирвать ValueObject

2024-08-15 13:06 UTC, YaraOduvanchik commented on backend/src/HelpAnimal.Infrastructure/Configuration/VolunteerConfiguration.cs
> +        builder.HasMany(v => v.Requisite)
Переделать, выше я приводил пример как конфигурирвать ValueObject

2024-08-15 13:06 UTC, YaraOduvanchik commented on backend/src/HelpAnimal.Infrastructure/HelpAnimalDbContext.cs
> +    public DbSet<HelpDetail> HelpDetails { get; set; }
Убрать этот DbSet, у нас взаимодействие через агреггаты Animal и Volunteer к другим таблицам

2024-08-15 13:06 UTC, YaraOduvanchik commented on backend/src/HelpAnimal.Infrastructure/HelpAnimalDbContext.cs
> +    public DbSet<SocialNetwork> SocialNetworks { get; set; }
Это тоже убрать

2024-08-15 13:06 UTC, YaraOduvanchik commented on backend/src/HelpAnimal.Infrastructure/HelpAnimalDbContext.cs
> +    public DbSet<AnimalPhoto> AnimalPhotos { get; set; }
Это тоже убрать

2024-08-15 13:08 UTC, YaraOduvanchik commented
> Подскажите насчет констант , в правильном направлении двигаюсь, нужно ли создавать константы для номера телефона ?

По поводу констант, общие константы ты можешь писать в классе Constants, а константы, которые относятсся к конкретным классам лучше всего писать в этих же классах

2024-08-17 06:35 UTC, YaraOduvanchik requested changes
В конфигурациях не убрал метод ValueGeneratedOnAdd у id. Его нужно убрать!

2024-08-17 10:24 UTC, YaraOduvanchik commented on backend/src/HelpAnimal.Domain/Models/AnimalPhoto.cs
> +    public AnimalPhoto()
пустой конструктор ненужен, это ValueObject

2024-08-17 14:25 UTC, merged